# Generated by Django 4.1.1 on 2022-10-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='activate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
