# Generated by Django 4.1.1 on 2022-10-08 07:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_delete_usercourses'),
        ('accounts', '0003_messages_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.DateTimeField(default=datetime.datetime(2022, 10, 8, 0, 38, 51, 326502))),
                ('courses', models.ManyToManyField(to='courses.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
