# Generated by Django 4.1.1 on 2022-10-03 08:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_usercourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourses',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 1, 28, 29, 22349)),
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
