# Generated by Django 4.1.1 on 2022-10-07 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_usercourses_added_alter_usercourses_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourses',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 2, 27, 45, 484403)),
        ),
    ]
