# Generated by Django 4.1.1 on 2022-10-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_usercourses_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourses',
        ),
    ]
